### ISSUE TITLE
question

### ISSUE THREAD

**Issue by FeynmanZhou** [sharding-sphere/sharding-sphere-doc#27]
Hi， 请教哈 sharding-sphere 的 docs 文档网站中的图是用什么工具画的呢？比如下面这种 :-D  @tristaZero 娟爷
![image](https://user-images.githubusercontent.com/40452856/47611596-77d87900-daa3-11e8-9062-13b8178e255c.png)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
